// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIJWbnPz93E5ktfvgPoaBfm1N362e_7Ig',
    appId: '1:542444962991:web:679f3b6782341de0cbc05a',
    messagingSenderId: '542444962991',
    projectId: 'plantapp-9fccd',
    authDomain: 'plantapp-9fccd.firebaseapp.com',
    storageBucket: 'plantapp-9fccd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkpEiUsGl916zxii4O22nPkWp4oTqqTdQ',
    appId: '1:542444962991:android:45df689342cd0472cbc05a',
    messagingSenderId: '542444962991',
    projectId: 'plantapp-9fccd',
    storageBucket: 'plantapp-9fccd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfrHDRq13v0BpioyNvjJJoI0BBgmuGcrk',
    appId: '1:542444962991:ios:603f7c10b7604ea1cbc05a',
    messagingSenderId: '542444962991',
    projectId: 'plantapp-9fccd',
    storageBucket: 'plantapp-9fccd.appspot.com',
    iosBundleId: 'com.example.plant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfrHDRq13v0BpioyNvjJJoI0BBgmuGcrk',
    appId: '1:542444962991:ios:603f7c10b7604ea1cbc05a',
    messagingSenderId: '542444962991',
    projectId: 'plantapp-9fccd',
    storageBucket: 'plantapp-9fccd.appspot.com',
    iosBundleId: 'com.example.plant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIJWbnPz93E5ktfvgPoaBfm1N362e_7Ig',
    appId: '1:542444962991:web:215b9a613f86662ecbc05a',
    messagingSenderId: '542444962991',
    projectId: 'plantapp-9fccd',
    authDomain: 'plantapp-9fccd.firebaseapp.com',
    storageBucket: 'plantapp-9fccd.appspot.com',
  );
}
